id: P6461685A
initial_creation_type: input
source_metadata:
  title: Geshe Chekhawa Yeshe Dorje
  language: en
  description: 'Texts by the famous Kadampa geshe Chekhawa Yeshe Dorje (''chad kha
    ba ye shes rdo rje, 1101–1175):'
  volume:
    a3ccc80804cb419eae0388ed4709c3a4:
      title: Seven Points of Training the Mind According to the Great Vehicle
      parent: null
created_at: '2022-02-28T23:23:01.280525'
last_modified_at: '2022-02-28T23:23:01.280533'
